name: Build

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  TARGET: x86_64-unknown-linux-musl
  NAME: server
  REPOSITORY: emotalk

permissions:
  contents: read
  id-token: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.ECR_ROLE }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ env.TARGET }}
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@master
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ env.TARGET }}
          use-cross: false
      - name: Move binary
        run: mv target/${{ env.TARGET }}/release/${{ env.NAME }} ${{ env.NAME }}/app

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v4
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY }}
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
